- name: build back
  tags: build_back
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - compile_back

- name: build front
  tags: build_front
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - compile_front

- name: build back img
  tags: build_back_img
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - mkbackimg

- name: build front img
  tags: build_front_img
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - mkfrontimg

- name: prepare db
  tags: prepare_db
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - prepdb

- name: setup controlplane
  hosts: controlplane
  gather_facts: true
  tags: setup_controlplane
  become: true
  vars:
    service_account_file: gcp_client_hsecret.json
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i ~/.ssh/google_compute_engine -J devops@bastion.us-central1-c.teachua-6147'
    projects: 
      - teachua-6147
    auth_kind: serviceaccount
  roles:
    - setupcontrolplane

- name: setup worker nodes
  hosts: gcp_group_instance_back_group
  gather_facts: true
  tags: setup_worker_nodes
  become: true
  vars:
    service_account_file: gcp_client_hsecret.json
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i ~/.ssh/google_compute_engine -J devops@bastion.us-central1-c.teachua-6147'
    projects: 
      - teachua-6147
    auth_kind: serviceaccount
  roles:
    - setupworkernodes

- name: deploy site
  hosts: controlplane
  gather_facts: true
  tags: deploy_site
  become: true
  vars:
    service_account_file: gcp_client_hsecret.json
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i ~/.ssh/google_compute_engine -J devops@bastion.us-central1-c.teachua-6147'
    projects: 
      - teachua-6147
    auth_kind: serviceaccount
  roles:
    - deploysite
