- name: copy compose.yml
  copy:
    src: ../../docker/frontend/compose.yml
    dest: "/root/compose.yml"

- name: stop previous container
  shell:
    cmd: docker compose down
  ignore_errors: true

- name: launch frontend container
  shell:
    cmd: docker compose up -d
    chdir: /root
