- name: get global address
  gcp_compute_global_address_info:
    project: teachua-6147
    auth_kind: serviceaccount
    service_account_file: ./gcp_client_hsecret.json
  register: global_address

- name: change .env
  template:
    src: roles/compile_front/templates/.env.production.j2
    dest: ../../frontend/.env.production

- name: copy shrinkwrap
  copy:
    src: roles/compile_front/files/npm-shrinkwrap.json
    dest: .../../frontend

- name: install deps
  shell:
    chdir: ../../frontend
    cmd: npm i

- name: build front
  shell:
    chdir: ../../frontend
    cmd: npm run build
