pipeline {
  agent any
  stages {
    stage ('Test') {
      steps {
        echo 'Hello world!'
        echo 'another step'
      }
    }
    stage ('Test dir info') {
      steps {
        sh 'pwd'
        sh 'echo I am $(whoami)'
        sh '''
          #!/usr/bin/zsh
          echo $0
          d /home/dima/files/project/softserve/internship/teachua/TeachUA-team
          pwd
          '''
      }
    }
  }
}
