pipeline {
  agent any
  stages {
    stage ('Test') {
      steps {
        echo 'Hello world!'
        echo 'another step'
      }
    }
    stage ('Test dir info') {
      steps {
        sh pwd
        sh cd /home/dima
        sh pwd
      }
    }
  }
}
