pipeline {
  agent any
  stages {
    stage ('Test') {
      steps {
        echo 'Hello world!'
        echo 'another step'
      }
    }
    stage ('build front') {
      steps {
        sh '''
          pwd
          ls -a
          '''
      }
    }
  }
}
