---
- name: get global address
  gcp_compute_global_address_info:
    project: teachua-6147
    auth_kind: serviceaccount
    service_account_file: ./gcp_client_hsecret.json
  register: global_address
  delegate_to: localhost
  become: true
  become_user: dima

- name: copy website
  copy:
    src: ../../frontend/build/
    dest: ../../docker/frontend/build
    force: true

- name: build image
  shell:
    cmd: docker build -t jimlinux/teachua-front:latest .
    chdir: ../../docker/frontend

#- name: generate compose.yml
#  template:
#    src: roles/mkfrontimg/templates/compose.yml.j2
#    dest: ../../docker/frontend/compose.yml

- name: publish image
  shell:
    cmd: docker push jimlinux/teachua-front:latest
