apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f backend/compose.yml -f frontend/compose.yml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: backend
  type: LoadBalancer
  externalIPs:
    - 192.168.0.197
